CREATE TABLE EMPLOYEE (
	SSN				INTEGER		    NOT NULL,
	FirstName		VARCHAR(50)		NOT NULL,
	LastName		VARCHAR(50)		NOT NULL,
	Sex				VARCHAR(10)		NOT NULL,
	Phone			VARCHAR(10)		NOT NULL,
	Email			VARCHAR(150)	NOT NULL,
	JobStartingDate	DATE			NOT NULL,
	Birthday		DATE			NOT NULL,	
	Address			VARCHAR(150)	NOT NULL,	
	Salary			INTEGER		    NOT NULL,	
PRIMARY KEY (SSN));

CREATE TABLE PROFESSOR (
	ProfId			INTEGER 	 NOT NULL,
	ManagerId		INTEGER,
	Profession		VARCHAR(50)	NOT NULL,
	FOREIGN KEY		(ProfId) REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY		(ManagerId) REFERENCES PROFESSOR(ProfId) ON DELETE SET NULL ON UPDATE CASCADE,
PRIMARY KEY (ProfId));

CREATE TABLE AUXILIARY_STAFF (
	EmployeeId		INTEGER NOT NULL,
	Profession		VARCHAR(50)	NOT NULL,
	FOREIGN KEY		(EmployeeId) REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY (EmployeeId));

CREATE TABLE PROJECT (
	ProfessorId		INTEGER NOT NULL,
	Name			VARCHAR(50)	NOT NULL,	
	Field			VARCHAR(50)	NOT NULL,
	Type			VARCHAR(50)	NOT NULL,
	Information		VARCHAR(500) NOT NULL,
	FOREIGN KEY		(ProfessorId) REFERENCES PROFESSOR(ProfId) ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY (Name, ProfessorId));

CREATE TABLE COURSE (
	CourseId		INTEGER	NOT NULL,
	Name			VARCHAR(50)	NOT NULL,	
	Semester		VARCHAR(2)	NOT NULL,
PRIMARY KEY (CourseId));

CREATE TABLE STUDENT (
    StudentId   INTEGER AUTO_INCREMENT 	NOT NULL,
    FirstName   VARCHAR(50)     		NOT NULL,
    LastName    VARCHAR(50)     		NOT NULL,
    FatherName  VARCHAR(50)     		NOT NULL,
    Sex         VARCHAR(10),
    Semester    TINYINT        			DEFAULT 1,
    Email       VARCHAR(150)   			NOT NULL,
    Phone       VARCHAR(10)    			NOT NULL,
    Birthday    DATE           			NOT NULL,
    EntryDate   DATE       				NOT NULL,
    Address     VARCHAR(255)   			NOT NULL,
    PRIMARY KEY (StudentId)
) AUTO_INCREMENT = 1054;

CREATE TABLE TEACHES (
	ProfId			INTEGER		NOT NULL,
	CourseId		INTEGER		NOT NULL,
	FOREIGN KEY		(ProfId) 	REFERENCES PROFESSOR (ProfId) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY		(CourseId) 	REFERENCES COURSE (CourseId) ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY (ProfId, CourseId));

CREATE TABLE ATTENDS (
	Grade			REAL		DEFAULT -1,
	StudentId		INTEGER		NOT NULL,
	CourseId		INTEGER		NOT NULL,
	FOREIGN KEY		(StudentId) REFERENCES STUDENT (StudentId) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY		(CourseId) 	REFERENCES COURSE (CourseId) ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY (StudentId, CourseId));
